### ISSUE TITLE
Netns-exporter works slow with hundreds of namespaces

### ISSUE THREAD

**Issue by AlexZzz** [velp/netns-exporter#1]
We've tried to run netns-exporter on a host with ~1146 network namespaces.

Time spent by curl for waiting of data collection:
```
real	1m21.932s
user	0m0.009s
sys	0m0.052s
```
Netns-exporter consumes about 25% of one cpu time in kernel space.

That would be awesome to have stats collected in 10-12 seconds, if possible, without high cpu consumption (no more than one cpu).

Call stack flamegraph:
![image](https://user-images.githubusercontent.com/5488460/81424457-a9350900-915e-11ea-9854-357c18dba1ca.png)

**Comment by velp** [comment]
Result of tests after PR #2 was merged
```
DEBU[0446] collecting took 13.220914997s for 1099 namespaces  component=collector
```
